# Generated by Django 5.2.8 on 2025-11-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('rescheduled', 'Rescheduled'), ('status_changed', 'Status Changed'), ('cancelled', 'Cancelled'), ('notes_updated', 'Notes Updated')], max_length=50)),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('previous_time', models.TimeField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_time', models.TimeField(blank=True, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='models.appointment')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appointment Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
