# Generated by Django 5.2.8 on 2025-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_appointmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=9, null=True),
        ),
    ]
