# Generated by Django 5.2.8 on 2025-11-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_serviceprovider_latitude_serviceprovider_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='models.conversations'),
        ),
    ]
