# Generated by Django 5.2.8 on 2025-11-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_basemodel_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
